### ISSUE TITLE
recommend里的slider组件加载有问题

### ISSUE THREAD

**Issue by Fiv5** [liutaochange/music-vue#1]
重现步骤:在create钩子里将getBannerList延迟1到2s, 模拟网速慢的情景, 当图片加载完毕后, 歌单不能滚动到底.

**Comment by Fiv5** [comment]
最简单的解决办法是给Slider组件增加一个监听事件setSliderWidthDone, 当Slider里的setSliderWidth方法调用完毕时, 去触发这个事件, 然后再去刷新better-scroll的refresh
<img width="474" alt="2018-04-01 3 54 18" src="https://user-images.githubusercontent.com/23014093/38171114-6bde2506-35c5-11e8-871e-05502b3817eb.png">
<img width="249" alt="2018-04-01 3 54 51" src="https://user-images.githubusercontent.com/23014093/38171116-6fc6c43e-35c5-11e8-8352-ff30cbd3a24b.png">
<img width="472" alt="2018-04-01 3 55 09" src="https://user-images.githubusercontent.com/23014093/38171118-765f8ace-35c5-11e8-9074-a8431d9af135.png">

**Comment by liutaochange** [comment]
首先感谢老铁提issue，发现了我没发现的问题，我修改过了，但是没有按照你的做法，我监听了下img的onload事件，重新触发一次scroll组件的刷新，可以测下看看

**Comment by liutaochange** [comment]
通过在slider组件里，调用nextTick的回调来监听图片的加载完成，可以解决问题，感谢老铁。

**Comment by liutaochange** [comment]
通过slider的nextTick回调来监听图片的加载完成，确实可以解决问题，谢谢老铁，已修复。
